// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNXwqM6ZPRM1qAgckjdnAzkdkq_i8GfA',
    appId: '1:742555950517:web:ed82320bb4ecc97b390dfc',
    messagingSenderId: '742555950517',
    projectId: 'nutrition-trackerapp',
    authDomain: 'nutrition-trackerapp.firebaseapp.com',
    storageBucket: 'nutrition-trackerapp.firebasestorage.app',
    measurementId: 'G-45GN9Q5Z08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3bqxITFJb3MlTYgciXNQEujGpfOAYNGY',
    appId: '1:742555950517:android:4e5ddd809cbe43df390dfc',
    messagingSenderId: '742555950517',
    projectId: 'nutrition-trackerapp',
    storageBucket: 'nutrition-trackerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvRtm5geNs2lzuoTMGceABxw1BxgLcbvM',
    appId: '1:742555950517:ios:7ef81c93bbb71221390dfc',
    messagingSenderId: '742555950517',
    projectId: 'nutrition-trackerapp',
    storageBucket: 'nutrition-trackerapp.firebasestorage.app',
    iosBundleId: 'com.m.nutrition.tracker.app',
  );
}
